export enum Features {
  MINT = 'MINT',
  LAZY_MINT = 'LAZY_MINT',
  REMINT = 'REMINT',
  SAVE_RIGHTS = 'SAVE_RIGHTS',
  EDIT_RIGHTS = 'EDIT_RIGHTS',
  UNIQUENESS_CHECKS = 'UNIQUENESS_CHECKS',
  ON_DEMAND_CHECKS = 'ON_DEMAND_CHECKS',
  POLICING = 'POLICING',
  TRANSFER_ASSET = 'TRANSFER_ASSET',
  PROTECT_NFT = 'PROTECT_NFT',
}
