export const endpoints = {
  Login: '/auth/login',
  Signup: '/auth/signup',
  Login2FA: '/auth/login-2FA',
  uploadImage: '/user/upload',
  Toggle2FA: '/auth/toggle-2FA',
  VerifyEmail: '/auth/verify-email',
  resendEmail: '/auth/resend-email',
  ResetPassword: '/auth/reset-password',
  Send2FA: '/auth/send-2FA-verification',
  ForgotPassword: '/auth/forgot-password',
  VerifyOTP: '/auth/verify-reset-password',
  checkUniqueness: '/mint/check-multiple-uniqueness',
  onDemandUniqueness: '/mint/ondemand-uniqueness',
  fiat: '/payment/subscribe/fiat-payment',
  freePlan: '/payment/subscribe/free-plan',
  plans: '/payment/plans',
  protectionOneTimePayment: '/payment/one-time-payment/loss-success-prevention',
};
