const CONFIG = {
  ENV: process.env.REACT_APP_NODE_ENV,
  BASE_URL: process.env.REACT_APP_SERVER_API,
  OPENSEA_URL: process.env.REACT_APP_OPENSEA_URL || '',
  REGISTRY_URL: process.env.REACT_APP_REGISTRY_URL || '',
  ETHERSCAN_URL: process.env.REACT_APP_ETHERSCAN_URL || '',
  VERSIONING_LINK: process.env.REACT_APP_VERSIONING_LINK || '',
  CONTRACT_ADDRESS: process.env.REACT_APP_CONTRACT_ADDRESS ?? '',
  GOOGLE_RECAPTCHA: process.env.REACT_APP_GOOGLE_RECAPTCHA || '',
  IPFS_URL_CONTACT: process.env.REACT_APP_IPFS_URL_CONTACT ?? '',
  STRIPE_PUBLIC_KEY: process.env.REACT_APP_STRIPE_PUBLIC_KEY ?? '',
  MIN_SUCCESSION_DAYS: process.env.REACT_APP_MIN_SUCCESSION_DAYS || '',
  WEB_SOCKET_BASE_URL: process.env.REACT_APP_SERVER_WEB_SOCKET_API ?? '',
  SUCCESSION_CONTRACT_ADDRESS: process.env.REACT_APP_SUCCESSION_CONTRACT_ADDRESS ?? '',
};

export default CONFIG;
